- sampling_method: flrs
  num_sampling_steps: [32]
  cfgs: [2]
  self_cond_cfg_scales: [1]
  rollback_gamma_start: 2.0
  rollback_gamma_end: 0.0
  time_schedule: logit_normal

- sampling_method: flrs
  num_sampling_steps: [16]
  cfgs: [2]
  self_cond_cfg_scales: [1]
  rollback_gamma_start: 2.0
  rollback_gamma_end: 0.0
  time_schedule: logit_normal
